<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>RamBook</title>

    <!-- include an external style sheet -->
    <link rel="stylesheet" href="style.css" />

    <!-- include an external JavaScript file -->
    <script src="script.js" defer></script>
  </head>
  
      <!-- include font families -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Arima+Madurai:wght@100&family=Baloo+2&family=Press+Start+2P&display=swap"
      rel="stylesheet"
    />

  <body>
	<div id="navButtons">
      <a href="?randNum=0">Funny names</a>
      <a href="?randNum=1">Random numbers</a>
      <a href="?randNum=2">Strange sayings</a>
      <a href="?randNum=3">Number grid</a>
      <a href="?randNum=4">Add profile</a>
      <a href="?randNum=5">View profiles</a>
    </div>
	<span onclick="test()">TEST</span>